FROM xataz/nginx-php

MAINTAINER hydrog3n <contact@loicvaille.ovh>

ARG VERSION_SHAARLI=0.10.4
ARG VERSION_MATERIAL=0.10.4

RUN cd /tmp \
    && wget https://github.com/shaarli/Shaarli/releases/download/v${VERSION_SHAARLI}/shaarli-v${VERSION_SHAARLI}-full.tar.gz \
    && tar xzf shaarli-v${VERSION_SHAARLI}-full.tar.gz \
    && mv /tmp/Shaarli /shaarli \
    && wget https://github.com/kalvn/Shaarli-Material/archive/v${VERSION_MATERIAL}.tar.gz \
    && tar xzf v${VERSION_MATERIAL}.tar.gz \
    && mv Shaarli-Material-${VERSION_MATERIAL}/material /shaarli/tpl/ \
    && rm -rf v${VERSION_MATERIAL}.tar.gz Shaarli-Material-${VERSION_MATERIAL} \
    && cd /shaarli && chmod +w cache pagecache data tmp \
    && apk del --quiet --no-cache --progress --purge && rm -rf /tmp/* /var/cache/apk/* /usr/src/*

COPY nginx/sites-enabled/shaarli.conf /nginx/sites-enabled/

COPY nginx/conf.d/*.conf /nginx/conf.d/

COPY startup /usr/local/bin/

RUN chmod +x /usr/local/bin/startup

VOLUME /shaarli

ENTRYPOINT ["/usr/local/bin/startup"]
CMD ["/bin/s6-svscan", "/etc/s6.d"]